jira:
  jira-secret: TpPAtnE3r9z3oct3ZhiP6812
  user-name: fawazalhosh@gmail.com
  base-url: https://kotlinbitvoodoo.atlassian.net
  ticket-url: /rest/api/2/issue
  project-key: BT
server:
  port: 8080
